### PR TITLE
Update outdated dependencies

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates outdated dependencies

## Testing

1. Running `yarn && yarn serve` should work.

### CODE REVIEW

**Comment by chosak** [comment]
The build fails for me with the same error as the check above:

```
ERROR in ./src/css/main.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):



.respond-to-min( @bp-sm-min, {
^
Error evaluating function `percentage`: argument must be a number
      Error in node_modules/@cfpb/cfpb-layout/src/cfpb-layout.less (line 129, column 0)
```

**Comment by anselmbradford** [comment]
> The build fails for me with the same error as the check above:

Blergh… we'll need to update to less 4 in the design-system repo, do a release, and then update here. I've downgraded `less` from `4.x` to its prior state of `3.x` for now.

**Review by chosak — COMMENTED** [review]
Build works for me now -- what's the reason for the .u-invisible change?

**Comment by anselmbradford** [comment]
> Build works for me now -- what's the reason for the .u-invisible change?

It's an update that's coming in from the DS added in https://github.com/cfpb/design-system/pull/1113/

**Review by chosak — APPROVED** [review]

**Pull request merged**
