### PR TITLE
Add Lighthouse report history pages

### PR DESCRIPTION
**Pull request by contolini**
Adds permalinks for each page w/ links to their historical results. It does so by reading all the reports in the `docs/reports/` directory and generating a JSON index of all the report data organized by both dates and pages. Webpack reads the JSON file and spits out an HTML file for each page.

Note: Ignore all the changes in the `docs/` directory. In a future PR we'll move all those files to their own branch and gitignore the directory.

## Changes

- Modified `index.njk` to accommodate the new data format and added `page.njk` for the new pages.
- Added scripts under `/scripts` for processing the reports. The entry point is `scripts/create-reports-index.js`.
- Tests in `test/` to validate the above scripts.

## Testing

1. Pull down this branch
1. `yarn` to install dependencies.
1. `yarn test` to ensure tests pass.
1. `yarn index-reports` to index all the reports in docs/reports/ and generate docs/reports.json. It will also delete extraneous report files.
1. `yarn build` to run webpack and generate the website (homepage and individual cf.gov pages) from reports.json.
1. `yarn serve` to server the docs/ directory locally and preview the site at http://127.0.0.1:8080/.
1. Click the "View report history" links to view individual pages' histories.

## Screenshots

Screen Shot 2020-10-14 at 2 40 28 PM

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by chosak** [comment]
With these changes there's some inconsistencies in the various GitHub Actions files:

- build-and-push.yml runs `yarn index-reports` then `yarn build`.
- build.yml runs `yarn index-reports` then `yarn build`.
- lighthouse.yml runs only `yarn index-reports` and doesn't run `yarn build`.

Shouldn't lighthouse.yml also run the build and, if so, is it worth just combining the two commands together into one?

**Comment by contolini** [comment]
Good call @chosak. I think we want lighthouse to only run once per day while the site should be built and deployed after every merged pr? How about these three workflows:

- `test.yml` that runs against opened pull requests and does `yarn lint` and `yarn test`.
- `build.yml `that runs against merged pull requests and builds and pushes the website.
- `lighthouse.yml` that runs nightly via cron and does `yarn lighthouse` before building and pushing the website.

**Comment by chosak** [comment]
@contolini that sounds good, but for the first one `test.yml`, did you mean `yarn build` instead of `yarn test`?

**Comment by contolini** [comment]
> Should we also do yarn build on PRs, to make sure the build doesn't break?

Yeah, that makes sense -- build it but not push it. 👍

**Review by chosak — APPROVED** [review]
Works great!

**Pull request merged**
